name: Execution

on:
  workflow_dispatch:
    inputs:
      browser:
        description: 'Select a browser, for example: chrome / electron'
        required: false
        default: 'chrome'
      tag:
        description: 'Select a tag, for example: @regression / @smoke / @login'
        required: false
        default: '@regression'
  pull_request:
    branches: [ master, release/develop ]
  push:
    branches: master  
  schedule: 
   - cron: "0 15 * * *"
   - cron: "0 18 * * *"
   - cron: "0 12 * * *"

env: 
  DEFAULT_BROWSER: "chrome"
  DEFAULT_TAG: "@regression"
  TZ: "America/Sao_Paulo"

jobs:
  test:
    name: Remove files from specific directory
        run:|
          rm -rf allure-results
    name: Cypress run
    runs-on: ubuntu-latest
    container: cypress/browsers:22.15.0
    steps:
      - name: Checkout
        uses: actions/checkout@v4     
      - name: Cypress run 
        uses: cypress-io/github-action@v6
        with: 
          command: npx cypress run --browser ${{github.event.inputs.browser || env.DEFAULT_BROWSER}} --env grepTags=${{github.event.inputs.tag || env.DEFAULT_TAG}}  allure=true --reporter mocha-allure-reporter 
      - name: Generate Allure Report
        uses: simple-elf/allure-report-action@master
        id: allure-report
        if: always()
        with:  
          allure_results: allure-results
          allure_history: allure-history
          gh_pages: gh-pages
          keep_reports: 20
      - name: Upload Allure Results
        uses: actions/upload-artifact@v4.0.0
        id: allure-results
        with:
          name: allure-results
          path: allure-results
          if-no-files-found: error
          retention-days: 20
        env: 
            GITHUB_TOKEN: ${{ github.token }} 
            MYID: ${{ steps.allure-results.outputs.artifact-id }}
            MYURL: ${{ steps.allure-results.outputs.artifact-url }}      
      - name: Output artifact URL
        run:  echo 'Allure report can be download on ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}/artifacts/${{ steps.allure-results.outputs.artifact-id }}'
      - name: Get Allure history (optional)
        uses: actions/checkout@v4.1.1
        if: always()
        continue-on-error: true
        with:
          ref: gh-pages
          path: gh-pages
      - name: Deploy report to Github Pages
        if: always()
        uses: peaceiris/actions-gh-pages@v2
        env:
          PERSONAL_TOKEN: ${{ github.token }} 
          PUBLISH_BRANCH: gh-pages
          PUBLISH_DIR: allure-history
